#sonar-flutter # Utiliza la imagen oficial de SonarQube
FROM sonarqube
# Expone el puerto en el que SonarQube está escuchando (predeterminado: 9000)
EXPOSE 9000
# URL del plugin de Flutter
ENV PLUGIN_URL="https://github.com/insideapp-oss/sonar-flutter/releases/download/0.5.3-SNAPSHOT/sonar-flutter-plugin-0.5.3-SNAPSHOT.jar"
# Descarga y coloca el plugin de Flutter en la ubicación correcta
RUN wget -O /opt/sonarqube/extensions/plugins/sonar-flutter-plugin.jar $PLUGIN_URL
EXPOSE 9000
