# Utiliza la imagen oficial de SonarQube
FROM sonarqube:lts-community

# Cambiar a usuario root para ejecutar comandos con permisos elevados
USER root

# Instalar dependencias necesarias (wget, ca-certificates, gosu)
RUN apt-get update && \
    apt-get install -y wget ca-certificates gosu && \
    rm -rf /var/lib/apt/lists/*

# Descargar e instalar AzCopy
RUN wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz && \
    tar -xf azcopy.tar.gz --strip-components=1 && \
    mv azcopy /usr/local/bin/ && \
    chmod +x /usr/local/bin/azcopy && \
    rm azcopy.tar.gz

# URL del plugin de Flutter
ENV PLUGIN_URL="https://github.com/insideapp-oss/sonar-flutter/releases/download/0.5.3-SNAPSHOT/sonar-flutter-plugin-0.5.3-SNAPSHOT.jar"

# Descarga y coloca el plugin de Flutter en la ubicación correcta
RUN wget -O /opt/sonarqube/extensions/plugins/sonar-flutter-plugin.jar $PLUGIN_URL

# Crear directorios necesarios y asignar permisos
RUN mkdir -p /opt/sonarqube/data /opt/sonarqube/logs && \
    chown -R sonarqube:sonarqube /opt/sonarqube/data /opt/sonarqube/extensions /opt/sonarqube/logs

# Copiar el script de entrada
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Exponer el puerto en el que SonarQube está escuchando (predeterminado: 9000)
EXPOSE 9000

# Usar el script de entrada personalizado
ENTRYPOINT ["/entrypoint.sh"]

